import { defineConfig } from 'tsup'

export default defineConfig([
  {
    entry: ['src/server/entries/node.ts'],
    outDir: 'dist/server',
    format: 'esm',
    platform: 'node',
    target: 'node18',
    clean: false,
    sourcemap: false,
    minify: true,
    external: [
      '@libsql/client',
      'mysql2',
      'ws',
      'drizzle-orm',
      'drizzle-orm/libsql',
      'drizzle-orm/libsql/migrator',
      'drizzle-orm/mysql2',
      'drizzle-orm/d1',
      'pino',
      'pino-pretty',
      'dotenv',
    ],
    treeshake: true,
    dts: false,
  },
  {
    entry: ['src/server/entries/cloudflare.ts'],
    outDir: 'dist/cloudflare',
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    clean: true,
    sourcemap: false,
    minify: true,
    treeshake: true,
    dts: false,
    noExternal: [
      'hono',
      '@hono/zod-openapi',
      '@hono/zod-validator',
      'zod',
      'drizzle-orm',
      'drizzle-orm/d1',
    ],
    external: [
      'pino',
      'pino-pretty',
      'dotenv',
      '@libsql/client',
      'mysql2',
      'ws',
      'drizzle-orm/libsql',
      'drizzle-orm/libsql/migrator',
      'drizzle-orm/mysql2',
      'path',
      'fs',
      'crypto',
      'http',
      'stream',
      'node:path',
      'node:fs',
      'node:crypto',
      'node:http',
      'node:stream',
    ],
    define: {
      'process.env.NODE_ENV': '"production"',
    },
  },
  {
    entry: ['src/cli/index.ts'],
    outDir: 'dist/cli',
    format: 'esm',
    platform: 'node',
    target: 'node18',
    clean: false,
    sourcemap: true,
    minify: false,
    treeshake: true,
    dts: true,
    banner: {
      js: '#!/usr/bin/env node',
    },
    external: ['hono', 'hono/client', 'commander', 'chalk', 'eslint'],
  },
])
