name = "xbrowser-marketplace"
main = "dist/cloudflare/cloudflare.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "xbrowser-marketplace-db"
database_id = "c18edb9b-4747-41f0-b31a-9f705421fbef"
migrations_dir = "migrations"

[[durable_objects.bindings]]
name = "REALTIME_DO"
class_name = "RealtimeDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["NotificationDurableObject"]

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "NotificationDurableObject", to = "RealtimeDurableObject" }]

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "xbrowser-plugins"

[dev]
port = 8787
local_protocol = "http"
