export {
  getFileStorageConfig,
  getUploadConfig,
  validateFile,
  saveFile,
  saveToTemp,
  readFileData,
  getFileStream,
  deleteFile,
  moveFile,
  cleanupTempFiles,
  clearNamespace,
  getFilePath,
  getPublicFileUrl,
  getPublicFilePath,
  fileExists,
  getFileInfo,
  type FileUploadConfig,
  type UploadedFile,
  type FileStorageConfig,
  type FileAccessOptions,
} from './file-storage-core'

export {
  generateSignature,
  verifySignature,
  getPrivateFileUrl,
  parseSignedUrl,
  getFileUrl,
  type SignedUrlParams,
} from './file-storage-signing'
