export const initialPermissions = [
  {
    id: 'perm_user_view',
    code: 'user:view',
    name: '查看用户',
    label: '查看用户',
    category: 'user',
    sortOrder: 1,
  },
  {
    id: 'perm_user_create',
    code: 'user:create',
    name: '创建用户',
    label: '创建用户',
    category: 'user',
    sortOrder: 2,
  },
  {
    id: 'perm_user_edit',
    code: 'user:edit',
    name: '编辑用户',
    label: '编辑用户',
    category: 'user',
    sortOrder: 3,
  },
  {
    id: 'perm_user_delete',
    code: 'user:delete',
    name: '删除用户',
    label: '删除用户',
    category: 'user',
    sortOrder: 4,
  },

  {
    id: 'perm_content_view',
    code: 'content:view',
    name: '查看内容',
    label: '查看内容',
    category: 'content',
    sortOrder: 10,
  },
  {
    id: 'perm_content_create',
    code: 'content:create',
    name: '创建内容',
    label: '创建内容',
    category: 'content',
    sortOrder: 11,
  },
  {
    id: 'perm_content_edit',
    code: 'content:edit',
    name: '编辑内容',
    label: '编辑内容',
    category: 'content',
    sortOrder: 12,
  },
  {
    id: 'perm_content_delete',
    code: 'content:delete',
    name: '删除内容',
    label: '删除内容',
    category: 'content',
    sortOrder: 13,
  },

  {
    id: 'perm_system_settings',
    code: 'system:settings',
    name: '系统设置',
    label: '系统设置',
    category: 'system',
    sortOrder: 20,
  },
  {
    id: 'perm_system_logs',
    code: 'system:logs',
    name: '查看日志',
    label: '查看日志',
    category: 'system',
    sortOrder: 21,
  },
  {
    id: 'perm_system_monitor',
    code: 'system:monitor',
    name: '系统监控',
    label: '系统监控',
    category: 'system',
    sortOrder: 22,
  },

  {
    id: 'perm_data_export',
    code: 'data:export',
    name: '数据导出',
    label: '数据导出',
    category: 'data',
    sortOrder: 30,
  },
  {
    id: 'perm_data_import',
    code: 'data:import',
    name: '数据导入',
    label: '数据导入',
    category: 'data',
    sortOrder: 31,
  },

  {
    id: 'perm_order_view',
    code: 'order:view',
    name: '查看订单',
    label: '查看订单',
    category: 'order',
    sortOrder: 40,
  },
  {
    id: 'perm_order_process',
    code: 'order:process',
    name: '处理订单',
    label: '处理订单',
    category: 'order',
    sortOrder: 41,
  },

  {
    id: 'perm_ticket_view',
    code: 'ticket:view',
    name: '查看工单',
    label: '查看工单',
    category: 'ticket',
    sortOrder: 50,
  },
  {
    id: 'perm_ticket_reply',
    code: 'ticket:reply',
    name: '回复工单',
    label: '回复工单',
    category: 'ticket',
    sortOrder: 51,
  },
  {
    id: 'perm_ticket_close',
    code: 'ticket:close',
    name: '关闭工单',
    label: '关闭工单',
    category: 'ticket',
    sortOrder: 52,
  },
]

export const initialRoles = [
  {
    id: 'role_super_admin',
    code: 'super_admin',
    name: '超级管理员',
    label: '超级管理员',
    isSystem: true,
    sortOrder: 1,
  },
  {
    id: 'role_customer_service',
    code: 'customer_service',
    name: '客服人员',
    label: '客服人员',
    isSystem: true,
    sortOrder: 2,
  },
  {
    id: 'role_user',
    code: 'user',
    name: '普通用户',
    label: '普通用户',
    isSystem: true,
    sortOrder: 3,
  },
]

export const initialRoutes = [
  {
    id: 'route_login',
    path: '/api/admin/login',
    method: 'POST',
    name: '登录',
    module: 'auth',
    isPublic: true,
  },
  {
    id: 'route_register',
    path: '/api/admin/register',
    method: 'POST',
    name: '注册',
    module: 'auth',
    isPublic: true,
  },
  {
    id: 'route_permissions',
    path: '/api/permissions',
    method: 'GET',
    name: '获取权限列表',
    module: 'permission',
    isPublic: true,
  },
  {
    id: 'route_roles',
    path: '/api/permissions/roles',
    method: 'GET',
    name: '获取角色列表',
    module: 'permission',
    isPublic: true,
  },

  {
    id: 'route_users_list',
    path: '/api/admin/users',
    method: 'GET',
    name: '获取用户列表',
    module: 'user',
    isPublic: false,
  },
  {
    id: 'route_users_create',
    path: '/api/admin/users',
    method: 'POST',
    name: '创建用户',
    module: 'user',
    isPublic: false,
  },
  {
    id: 'route_users_update',
    path: '/api/admin/users/:id',
    method: 'PUT',
    name: '更新用户',
    module: 'user',
    isPublic: false,
  },
  {
    id: 'route_users_delete',
    path: '/api/admin/users/:id',
    method: 'DELETE',
    name: '删除用户',
    module: 'user',
    isPublic: false,
  },

  {
    id: 'route_content_list',
    path: '/api/content',
    method: 'GET',
    name: '获取内容列表',
    module: 'content',
    isPublic: false,
  },
  {
    id: 'route_content_create',
    path: '/api/content',
    method: 'POST',
    name: '创建内容',
    module: 'content',
    isPublic: false,
  },
  {
    id: 'route_content_update',
    path: '/api/content/:id',
    method: 'PUT',
    name: '更新内容',
    module: 'content',
    isPublic: false,
  },
  {
    id: 'route_content_delete',
    path: '/api/content/:id',
    method: 'DELETE',
    name: '删除内容',
    module: 'content',
    isPublic: false,
  },

  {
    id: 'route_settings',
    path: '/api/admin/settings',
    method: 'GET',
    name: '获取系统设置',
    module: 'system',
    isPublic: false,
  },
  {
    id: 'route_settings_update',
    path: '/api/admin/settings',
    method: 'PUT',
    name: '更新系统设置',
    module: 'system',
    isPublic: false,
  },
  {
    id: 'route_logs',
    path: '/api/admin/logs',
    method: 'GET',
    name: '获取系统日志',
    module: 'system',
    isPublic: false,
  },
]

export const initialRolePermissions = [
  { roleId: 'role_super_admin', permissionId: 'perm_user_view' },
  { roleId: 'role_super_admin', permissionId: 'perm_user_create' },
  { roleId: 'role_super_admin', permissionId: 'perm_user_edit' },
  { roleId: 'role_super_admin', permissionId: 'perm_user_delete' },
  { roleId: 'role_super_admin', permissionId: 'perm_content_view' },
  { roleId: 'role_super_admin', permissionId: 'perm_content_create' },
  { roleId: 'role_super_admin', permissionId: 'perm_content_edit' },
  { roleId: 'role_super_admin', permissionId: 'perm_content_delete' },
  { roleId: 'role_super_admin', permissionId: 'perm_system_settings' },
  { roleId: 'role_super_admin', permissionId: 'perm_system_logs' },
  { roleId: 'role_super_admin', permissionId: 'perm_system_monitor' },
  { roleId: 'role_super_admin', permissionId: 'perm_data_export' },
  { roleId: 'role_super_admin', permissionId: 'perm_data_import' },
  { roleId: 'role_super_admin', permissionId: 'perm_order_view' },
  { roleId: 'role_super_admin', permissionId: 'perm_order_process' },
  { roleId: 'role_super_admin', permissionId: 'perm_ticket_view' },
  { roleId: 'role_super_admin', permissionId: 'perm_ticket_reply' },
  { roleId: 'role_super_admin', permissionId: 'perm_ticket_close' },

  { roleId: 'role_customer_service', permissionId: 'perm_user_view' },
  { roleId: 'role_customer_service', permissionId: 'perm_content_view' },
  { roleId: 'role_customer_service', permissionId: 'perm_order_view' },
  { roleId: 'role_customer_service', permissionId: 'perm_order_process' },
  { roleId: 'role_customer_service', permissionId: 'perm_ticket_view' },
  { roleId: 'role_customer_service', permissionId: 'perm_ticket_reply' },
  { roleId: 'role_customer_service', permissionId: 'perm_ticket_close' },
  { roleId: 'role_customer_service', permissionId: 'perm_data_export' },
  { roleId: 'role_customer_service', permissionId: 'perm_system_logs' },

  { roleId: 'role_user', permissionId: 'perm_content_view' },
  { roleId: 'role_user', permissionId: 'perm_order_view' },
]

export const initialPermissionRoutes = [
  { permissionId: 'perm_user_view', routeId: 'route_users_list' },
  { permissionId: 'perm_user_create', routeId: 'route_users_create' },
  { permissionId: 'perm_user_edit', routeId: 'route_users_update' },
  { permissionId: 'perm_user_delete', routeId: 'route_users_delete' },

  { permissionId: 'perm_content_view', routeId: 'route_content_list' },
  { permissionId: 'perm_content_create', routeId: 'route_content_create' },
  { permissionId: 'perm_content_edit', routeId: 'route_content_update' },
  { permissionId: 'perm_content_delete', routeId: 'route_content_delete' },

  { permissionId: 'perm_system_settings', routeId: 'route_settings' },
  { permissionId: 'perm_system_settings', routeId: 'route_settings_update' },
  { permissionId: 'perm_system_logs', routeId: 'route_logs' },
]
